version: 2.0.0.{build}

# Use 2017 Image :)
image:
- Visual Studio 2017 RC

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

cache:
- packages -> packages\packages.config

before_build:
- nuget restore

build:
  publish_nuget: true

deploy:
- provider: NuGet
  api_key:
    secure: kTNf1aNQVwwimPmGQreJV8UrGI1jBSUiwiTgThlyLZM4tKPguC0ZmSPi8+s7hd4M
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
